-- AMFramework objects
-- require"json.json"
require"Objects.AM_StringManipulators"
require"Objects.Configuration"
require"Objects.Element"
require"Objects.ElementComposition"
require"Objects.EquilibriumConfig"
require"Objects.EquilibriumPhaseFraction"
require"Objects.Phase"
require"Objects.ScheilConfig"
require"Objects.ScheilPhaseFraction"
require"Objects.SelectedElement"
require"Objects.SelectedPhase"
require"Objects.Case"
require"Objects.Project"
require"Objects.ActivePhases"
require"Objects.ActivePhasesConfig"
require"Objects.ActivePhasesElementComposition"
require"Objects.PrecipitateSimulationData"
require"Objects.PrecipitationPhase"
require"Objects.PrecipitationDomain"
require"Objects.HeatTreatment"
require"Objects.HeatTreatmentProfile"
require"Objects.HeatTreatmentSegment"
require"Objects.Framework"

print("loaded!")