#pragma once
#include "../../../interfaces/IAM_DBS.h"



/* ------------------------------------------------------
File generated by cmake script. This is a standard

template and will only be generated if the file does

not exist, feel free to edit.

*/// ----------------------------------------------------

namespace TRIGGERS
{

	class DBSTriggers_PrecipitateSimulationData
	{
	private:
		/// <summary>
		/// Static class
		/// <summary>
		DBSTriggers_PrecipitateSimulationData() {};
	public:
		/// <summary>
		/// Data trigger that removes data based on the heat treatment ID
		/// </summary>
		/// <param name="database"></param>
		/// <param name="htID"></param>
		/// <returns></returns>
		static int remove_precipitatePhase_data(IAM_Database* database, int pPhaseID)
		{
			std::string query = AMLIB::TN_PrecipitateSimulationData().columnNames[1] +
				" = " + std::to_string(pPhaseID);

			return database->remove_row(&AMLIB::TN_PrecipitateSimulationData(), query);
		}
	};
}
