#pragma once
#include "../../../interfaces/IAM_DBS.h"



/* ------------------------------------------------------
File generated by cmake script. This is a standard

template and will only be generated if the file does

not exist, feel free to edit.

*/// ----------------------------------------------------

namespace TRIGGERS
{

	class DBSTriggers_PrecipitateSimulationData
	{
	private:
		/// <summary>
		/// Static class
		/// <summary>
		DBSTriggers_PrecipitateSimulationData() {};
	public:
		// Add your static data-triggers here.
	};
}
