#pragma once
#include "../../../interfaces/IAM_DBS.h"



/* ------------------------------------------------------
File generated by cmake script. This is a standard

template and will only be generated if the file does

not exist, feel free to edit.

*/// ----------------------------------------------------

namespace TRIGGERS
{

	class DBSTriggers_HeatTreatmentSegment
	{
	private:
		/// <summary>
		/// Static class
		/// <summary>
		DBSTriggers_HeatTreatmentSegment() {};
	public:
		/// <summary>
		/// Data trigger that removes data based on the heat treatment ID
		/// </summary>
		/// <param name="database"></param>
		/// <param name="htID"></param>
		/// <returns></returns>
		static int remove_ht_data(IAM_Database* database, int htID)
		{
			std::string query = AMLIB::TN_HeatTreatmentSegments().columnNames[2] +
				" = " + std::to_string(htID);

			return database->remove_row(&AMLIB::TN_HeatTreatmentSegments(), query);
		}
	};
}
