#pragma once
#include "../../../interfaces/IAM_DBS.h"
#include "DBSTrigger_HeatTreatmentProfile.h"
#include "DBSTrigger_HeatTreatmentSegment.h"



/* ------------------------------------------------------
File generated by cmake script. This is a standard

template and will only be generated if the file does

not exist, feel free to edit.

*/// ----------------------------------------------------

namespace TRIGGERS
{

	class DBSTriggers_HeatTreatment
	{
	private:
		/// <summary>
		/// Static class
		/// <summary>
		DBSTriggers_HeatTreatment() {};

		/// <summary>
		/// Removes a heat treatment element
		/// </summary>
		/// <param name="database">database pointer</param>
		/// <param name="caseID">case ID</param>
		/// <returns>returns 0 when successful</returns>
		static int remove_ht_object(IAM_Database* database, int caseID)
		{	
			std::string query = AMLIB::TN_HeatTreatment().columnNames[1] +
				" = " + std::to_string(caseID);

			return database->remove_row(&AMLIB::TN_HeatTreatment(), query);
		}

	public:
		/// <summary>
		/// Removes a case row entry
		/// </summary>
		/// <returns></returns>
		static int remove_case_data(IAM_Database* database, int caseID)
		{
			// Load all cases and delete related data
			std::string queryCase = AMLIB::TN_HeatTreatment().columnNames[1] +
				" = " + std::to_string(caseID);

			AM_Database_Datatable dataList(database, &AMLIB::TN_HeatTreatment());
			dataList.load_data(queryCase);

			for (int n1 = 0; n1 < dataList.row_count(); n1++)
			{
				remove_ht_data(database, std::stoi(dataList(0, n1)));
			}

			// remove heat treatment objects
			remove_ht_object(database, caseID);

			return 0;
		}

		/// <summary>
		/// Data trigger that removes dependent data based on case ID
		/// </summary>
		/// <param name="database">Database pointer</param>
		/// <param name="caseID">Case ID</param>
		/// <returns></returns>
		static int remove_ht_data(IAM_Database* database, int htID) 
		{
			DBSTriggers_HeatTreatmentProfile::remove_ht_data(database, htID);
			DBSTriggers_HeatTreatmentSegment::remove_ht_data(database, htID);
			return 0;
		}
	};
}
